import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "./context/UserContext";
import Provider from "./context/Provider";
import Tabs from "./components/Tabs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="homeBackground bg-bgMain">
        <Provider>
          <UserProvider>
            {children}
            <Tabs />
          </UserProvider>
        </Provider>
      </body>
    </html>
  );
}
