import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "./context/UserContext";
import Tabs from "./components/Tabs";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <UserProvider>
            {children}
            <Tabs />
          </UserProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
